- name: cart
  hosts: cart
  become: yes
  vars_files:
  - variables.yaml
  tasks:
  - name: disabling old nodejs and enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: removing the old app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download the cart application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp
  
  - name: extract cart application
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copy cart service
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: daemopn reload and start
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable cart
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: yes
