- name: install web component
  hosts: web
  become: yes
  vars_files:
  - variables.yaml

- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: removing the default html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: creating html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download the web app
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /tmp

- name: extract the frondend code
  ansible.builtin.unarchive: 
    src: /tmp/web.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copy roboshop configuration
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes